repository_type: pipeline

nf_core_version: 3.2.0

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-polyamod_logo_light.png
    - docs/images/nf-core-polyamod_logo_light.png
    - docs/images/nf-core-polyamod_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-polyamod_logo_light.png
    - docs/images/nf-core-polyamod_logo_light.png
    - docs/images/nf-core-polyamod_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: nf-core
  name: polyamod
  description: A Nextflow pipeline designed to analyze RNA at the transcript level,
    providing poly(A) tail length estimation and RNA modification detection.
  author: Sahiti Somalraju
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - multiqc
    - fastqc
    - adaptivecard
    - slackreport
  is_nfcore: false
