name: prep_fastq
description: To merge multiple FASTQ files into one and convert to FASTA format
input:
  - fastq_dir:
        type: directory
        description: directory containing FASTQ files
output:
  - fastq_output:
        type: file
        path: ${params.output_dir}/${params.output_name}.fastq 
        description: merged FASTQ file
  - fasta_output:
        type: file
        path: ${params.output_dir}/${params.output_name}.fasta
        description: converted FASTA file 

