---
name: "m6anet"
description: Python package for detection of m6a modifications from Nanopore direct RNA sequencing data
keywords:
  - m6a
  - nanopore
tools:
  - "m6anet":
        description: Python package for detection of m6a modifications from Nanopore direct RNA sequencing data
        homepage: https://github.com/GoekeLab/m6anet
        license: ['MIT']

input:
  - eventalign_output:

output:
  - 
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@jonathangoeke"
maintainers:
  - "@jonathangoeke"
