name: samtools_view
description: filter/convert SAM/BAM/CRAM file
keywords:
  - view
  - bam
  - sam
tools:
  - samtools:
      description: filter/convert SAM/BAM/CRAM file
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
    - sam:
        type: file
        description: SAM file
	pattern: "*.{sam}"
output:
    - bam:
         type: file
         description: converted BAM file
         pattern: "*.{bam}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@joseespinosa"
  - "@FriederikeHanssen"
  - "@priyanka-surana"
maintainers:
  - "@drpatelh"
  - "@joseespinosa"
  - "@FriederikeHanssen"
  - "@priyanka-surana"
